name: API Checker
abbreviation: apichecker
checker: PragmaRX\Health\Checkers\Http
notify: true
column_size: 3
timeout_message: "[TIMEOUT] A request to %s took %s seconds. Timeout is set to %s seconds."
connection_timeout: 5
roundtrip_timeout: 10
targets:
  - default:
      urls:
        - http://strangecat-api.test/api/v1/ping:
            method: GET
            auth:
              - "{{ config('services.whatever.api.username') }}"
              - "{{ config('services.whatever.api.password') }}"
              - basic
